### PR TITLE
Use internal channel nsls2-tag

### PR DESCRIPTION
**Pull request by mrakitin**
This change will make the Docker image in sync with our current approach of using internal channels for both building and deployment.

### CODE REVIEW

**Comment by tacaswell** [comment]
don't we also need to adjust the server it is looking at as well?

**Comment by mrakitin** [comment]
I'm not sure I understood...

Anyway, with this approach even Python cannot be installed if it's build on a laptop. I think it should use the current approach, and at the end of generation the `.condarc` file can be changed to use the internal `nsls2-tag` channel instead of the external `lightsource2-tag` one. What do you think?

**Comment by licode** [comment]
When docker pull the image to build, conda channel is re-defined again, https://github.com/NSLS-II/lightsource2-recipes/blob/master/scripts/nsls2-tag-build.sh#L50. So the pre-defined parameters here can be overwritten.

But if we use this internally, conda will look at internal nsls2-tag and outside defaults, maybe using  http://alexandria/conda/defaults ?

**Comment by mrakitin** [comment]
Agree. Ideally we would need to use the same channels for building as we use on the floor, but it is not possible until freyja has the channels available.

**Comment by licode** [comment]
right, let's wait a little bit when freyja is ready.

**Comment by mrakitin** [comment]
I think I'll just close this PR for now as it won't directly work outside of NSLS-II.

**Pull request closed without merging**
