### PR TITLE
BLD: make image up-to-date

### PR DESCRIPTION
**Pull request by mrakitin**
Pulling some stuff from [lightsource2-recipes
](https://github.com/NSLS-II/lightsource2-recipes/blob/3f21d7e14422073e51feb062c65dbb7de22dc055/scripts/nsls2-tag-build.sh#L43-L74)

### CODE REVIEW

**Review by danielballan — APPROVED** [review]

**Comment by mrakitin** [comment]
@danielballan, thanks for reviewing this!
@licode, what do you think of the update? Do you mind to review and merge it? Thanks.

**Comment by mrakitin** [comment]
Summary of the recent updates:
- Miniconda 4.5.11 already has Python 3.7 as a default interpreter, so we use version 4.5.4 which still uses Python 3.6
- Get rig of the conda-forge channel and use `slacker` from https://anaconda.org/lightsource2-tag/slacker

**Comment by tacaswell** [comment]
Is this ready to go?

**Comment by mrakitin** [comment]
Yes.

**Comment by mrakitin** [comment]
Maybe `DOCKER_ID_USER=mrakitin` should be replaced with `DOCKER_ID_USER=nsls2`.

**Comment by licode** [comment]
LGTM.

**Pull request merged**
